dist: trusty

language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: true
script: ./gradlew build

notifications:
  email: false
  webhooks:
      urls:
        - "https://webhooks.gitter.im/e/163b47e78a566a5e0084"
      on_success: change  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: never     # options: [always|never|change] default: always